backtick-se/cowait

cowait/engine/kubernetes.py
cowait/tasks/agent/agent.py
cowait/tasks/agent/tasklist.py
cowait/tasks/definition.py

Agent: task monitoring

---

.github/workflows/build_images.yml
.github/workflows/tests.yml
build.sh
publish.sh
setup.py

Todo: 
- PyPi publish
- Crash if version already exists on PyPi
resolve #66

CI: Automated Image Build/Publish

---

cowait/tasks/remote_task.py

- Raise error when passing positional arguments to RPC methods
- Raise error when attempting RPC on a task that is not in the correct state (not running)
resolve #109

Improved RPC errors

---

cloud/src/components/task/TaskActionBar/StopButton.tsx
cloud/src/store/tasks/sagas.ts
cowait/engine/api.py
cowait/tasks/components/rpc.py

Introduces changes in the HTTP RPC protocol that will make future improvements easier.
resolve #129

HTTP RPC Protocol Changes

---

cowait/cli/commands/build.py
cowait/cli/logger.py
cowait/cli/task_image.py

- Streaming build logs
- Bonus: Gets rid of temporary dockerfiles
resolve #142

Streaming docker build output

---

cowait/engine/__init__.py
cowait/engine/cluster.py
cowait/engine/const.py
cowait/engine/test_cluster.py
cowait/engine/utils.py
cowait/worker/env.py

Task input compression & length check

---

Dockerfile
bin/cowait
cowait/cli/commands/__init__.py
cowait/cli/commands/notebook.py
cowait/engine/docker.py
cowait/engine/kubernetes.py
cowait/engine/routers/local_port_router.py
cowait/network/server.py
cowait/notebook/__init__.py
cowait/notebook/jupyter/jupyter_config.py
cowait/notebook/jupyter/kernel.py
cowait/notebook/jupyter/startup.py
cowait/notebook/node.py
cowait/notebook/spawn.py
cowait/notebook/task.py
cowait/tasks/agent/agent.py
cowait/tasks/components/task_manager.py
cowait/tasks/dask/cluster.py
cowait/tasks/dask/types.py
cowait/tasks/decorator.py
cowait/tasks/pickled/__init__.py
cowait/tasks/pickled/pickle_task.py
cowait/tasks/pickled/pickled_task.py
cowait/tasks/remote_task.py
cowait/tasks/shell/shell.py
cowait/tasks/spark/cluster.py
cowait/tasks/task.py
cowait/worker/parent_client.py
cowait/worker/worker_node.py
setup.py

Cowait Notebooks

---

Pipfile
Pipfile.lock
bin/cowait
cowait/cli/commands/agent.py
cowait/cli/commands/build.py
cowait/cli/commands/cluster.py
cowait/cli/commands/misc.py
cowait/cli/commands/new_context.py
cowait/cli/commands/run.py
cowait/cli/commands/test.py
cowait/cli/config.py
cowait/cli/context.py
cowait/cli/settings_dict.py
cowait/cli/task_image.py
cowait/cli/test_context.py
cowait/cli/test_settings_dict.py
setup.py

- Improved separation between global/context configuration
- `CowaitConfig` and `CowaitConfig` now derive from a common base `SettingsDict`
- Cleanup of CLI commands

CLI Refactor & Dotenv support

---

.dockerignore
bin/cowait
cowait/cli/commands/run.py
cowait/cli/context.py
cowait/engine/kubernetes.py
cowait/notebook/kernel.py
cowait/notebook/task.py
cowait/tasks/agent/agent.py
cowait/tasks/components/task_manager.py
cowait/tasks/dask/cluster.py
cowait/tasks/definition.py
cowait/tasks/instance.py
cowait/tasks/remote_task.py
cowait/tasks/spark/cluster.py
cowait/tasks/task.py
cowait/tasks/test_task_definition.py
cowait/test/test_task.py
cowait/utils/__init__.py
cowait/utils/version.py
cowait/worker/executor.py
cowait/worker/parent_client.py

resolve #72
resolve #150 
resolve #151 
resolve #158 
resolve #159

TASK_INIT Version & Separation of TaskDefinition and TaskInstance

---

cowait/exec.py
cowait/tasks/__init__.py
cowait/tasks/agent/tasklist.py
cowait/tasks/components/task_manager.py
cowait/tasks/definition.py
cowait/tasks/instance.py

Recent refactoring of TaskInstances/TaskDefinition seems to have broken some deserialization code, this will fix it

Fix deserialization of TaskDefinition/TaskInstances

---

cowait/engine/cluster.py
cowait/tasks/definition.py

Cast all environment values to strings

---

examples/10-imdb/cowait.yml
examples/10-imdb/imdb.py
examples/10-imdb/requirements.txt
examples/10-imdb/test_imdb.py

Binary text classification example with IMDB reviews dataset
- named it 10-imdb, pls change if desired :) 
- similar complexity as the mnist example
- copied the requirements.txt from the mnist example, don't know if everything is needed

nlp text classification example with imdb dataset

---

Pipfile.lock
cowait/engine/docker.py
cowait/engine/test_docker.py
setup.py

Fixes issues caused by the problem described here: https://github.com/docker/docker-py/issues/2696

Workaround for Docker API response problem in Docker for Mac

---

cowait/cli/commands/run.py
cowait/worker/loader.py

Improve task import/parse erors

---

cowait/cli/commands/notebook.py
cowait/notebook/task.py
images/docker-compose.yml
images/notebook/Dockerfile
images/notebook/requirements.txt
images/spark/Dockerfile

Created a container image that bundles jupyterlab and a few other dependencies required by Cowait notebooks.
Also, updates the Spark image to use 3.0.1.
resolve #227

Separate Notebook Container Image

---

cowait/cli/commands/run.py
cowait/cli/task_image.py

Long awaited feature! 😬 
`cowait run` will check for missing images, and pull them if necessary.
resolve #26

Automatically pull missing images when using DockerProvider

---

cowait/cli/commands/cluster.py
cowait/cli/commands/push.py

Adds vaildation & ability to add kubernetes cluster to `cowait cluster add`
resolve #237

cowait cluster add: required options & kubernetes support

---

cowait/cli/app/utils.py
test/cli/app/test_utils.py

CLI key-value args should default to string

---

cowait/cli/app/image.py
cowait/cli/commands/build.py
cowait/cli/commands/push.py

Add --push option to cowait build

---

cowait/network/server.py

Fix unhandled exception from ping on closed websocket

---

cowait/cli/commands/run.py
cowait/cli/context.py

properly read dotenv files

---

cowait/cli/commands/new_context.py
cowait/cli/config.py

Fix 'cowait new' command

---

cowait/cli/commands/build.py
cowait/cli/commands/push.py
cowait/cli/commands/run.py

Nonzero exit codes for failures in build/push/run

---

.gitignore
docs/quick-start.md

- Removed docs from gitignore
- Added test quick-start.md for external documentation building

Add example quickstart docs

---

cowait/engine/routers/traefik2_router.py

- Cast port numbers to integers
- Properly clean up IngressRoutes on exit
- Add support for configuring certificate resolvers

Traefik2 fixes

---

cowait/tasks/container/container_task.py

Fix ContainerTask

---

cowait/network/rpc_client.py

Refactor to avoid a potential race condition where the `RpcCall` object may be deleted from the pending call list before reaching the `wrap_future`
resolve #308

Fix RPC call race condition

---

cowait/cli/app/task.py
cowait/cli/commands/test.py

Add resource limit arguments to cowait test

---

cowait/utils/file_capture.py
cowait/utils/stream_capture.py
cowait/worker/executor.py
cowait/worker/logger/json_logger.py
cowait/worker/worker_node.py

Allows capturing of subprocess output.
Implementation based on pytest's `FDCapture`

File descriptor based output capturing
