.flake8, cowait/engine/test_docker.py, cowait/network/client.py, cowait/tasks/remote_task.py, cowait/test/tasks/utility_task.py, cowait/utils/emitter.py, cowait/worker/executor.py
- Added tests for failed tasks (DockerProvider)
- Await orphaned subtasks after execution
- Agent properly stores task errors
- Set max line witdth to 100 chars
resolve #97 
resolve #55
=> Await orphaned tasks, task failure tests & agent error storage fix

bin/cowait, cowait/engine/docker.py, cowait/engine/kubernetes.py, cowait/engine/routers/__init__.py, cowait/engine/routers/traefik2_router.py, cowait/worker/worker_node.py, k8setup.yml
- Adds a new `Traefik2Router` that can create Ingress Routes for Traefik 2.
- Router type is now configurable using the `router` cluster option.
- Routers may store additional configuration in the cluster options.
Configuration example:
```yaml
clusters:
kubernetes:
domain: cluster.yourcompany.com
router: traefik2
traefik2:
entrypoints:
- web
middlewares:
- https-only
```
resolve #36
=> Traefik 2 Support

cowait/engine/kubernetes.py
Fixes a bug where short lived containers would never be marked as completed because they finish before the `KubernetesProvider.spawn()` call returns.
`spawn()` no longer waits for the pod to become ready, which is likely fine since we have timeout logic elsewhere. `logs()` still need the pod to be ready however (otherwise kubernetes throws an error) so the `wait_until_ready()` call has been moved there.
=> Kubernetes: move wait_until_ready from spawn() to logs()

cowait/types/__init__.py, cowait/types/custom.py, cowait/types/dict.py, cowait/types/list.py, cowait/types/mapping.py, cowait/types/simple.py, cowait/types/test_serialization.py, cowait/types/test_types.py, cowait/types/test_utils.py, cowait/types/type.py, cowait/types/utils.py
Cowait Types must be serializable themselves. This allows us to return complex custom types from tasks and RPC calls.
This PR implements a _type description_ that can be returned along with a value. This description allows the type system to deserialize the type itself, and use this type to deserialize the value. If the type is not known to the caller, an error will be thrown.
**Example**
```js
{
// task data...
"result": {
"spark": {
"master_uri": "spark://whatever"
}
},
"result_type": {
"spark": "cowait.spark.types.SparkContext"
}
}
```
Because the `cowait.spark.types.SparkContext` type is built in (and thus always known to the caller), a `SparkContext` object can be passed directly between tasks without manual serialization.
=> Type Descriptions

cowait/cli/commands/run.py, cowait/engine/test_docker.py
Cowait has probably not been tested on WSL2, where things might be a little bit different. I made two small changes that enabled tests and examples to run on my wsl2 setup.
=> Enable WSL2 use of cowait

bin/cowait, cowait/cli/commands/run.py, cowait/engine/docker.py, cowait/engine/errors.py, cowait/engine/kubernetes.py, cowait/tasks/definition.py, cowait/tasks/task.py, cowait/tasks/test_task_definition.py
- Generic way to define volumes between docker & kubernetes
- Support for `bind` and `tmpfs` volumes in docker
- Auto mount task context directory
- Volume configuration in cowait context
```yml
version: 1
cowait:
volumes:
/var/dst/path:
bind:
src: /host/path
mode: 'ro'
/var/other:
bind: /hello
```
resolve #52
=> Volume Mount Support

cowait/engine/kubernetes.py
Adds a Service Account option to the `KubernetesProvider`. This fine grained control of cluster permissions for specific tasks.
```yml
clusters:
kubecluster:
type: kubernetes
context: kubecluster
namespace: my-task-namespace
service_account: my-service-account
```
resolve #99
=> Kubernetes: Add service account setting

Pipfile, Pipfile.lock, cowait/types/__init__.py, cowait/types/mapping.py, cowait/types/numpy.py, cowait/types/simple.py, cowait/types/test_numpy.py, setup.py
- Add numpy as a core dependency
- Create cowait type mappings for numpy types
- Use best-guess serialization of `Any` type.
=> Numpy Support

cowait/cli/commands/agent.py, cowait/engine/routers/local_port_router.py, cowait/engine/routers/traefik2_router.py, cowait/network/auth_middleware.py, cowait/tasks/agent/agent.py, cowait/tasks/components/rpc.py, cowait/tasks/dask/cluster.py, cowait/tasks/definition.py, cowait/tasks/errors.py, cowait/tasks/remote_task.py, cowait/tasks/spark/cluster.py, cowait/tasks/task.py, cowait/tasks/test_task_definition.py, cowait/types/simple.py, cowait/types/utils.py, cowait/utils/stream_capture.py, cowait/worker/executor.py, cowait/worker/parent_client.py
- Agent always runs on port 1339 in Docker
- Agent no longer requires token authentication in Docker
- Improved support for stopping tasks
- Stop orphan tasks instead of using `ClusterProvider.destroy()`
- Fix a bug in `StreamCapture`
- Fix a typo in `Traefik2Router`
resolve #136
=> Improved Stopping, Agent Tweaks etc

Dockerfile, bin/cowait, cowait/cli/commands/build.py, cowait/cli/context.py, cowait/cli/task_image.py, cowait/cli/test_context.py
Allows tasks to run from a subdirectory of the task image context. Everything in the context (defined as the folder containing `cowait.yml`) will still be copied into the `/var/task` folder of the image, but the working directory will be set to the specified subdirectory. This makes it possible to keep cowait tasks out of the project root. When the working directory option is set, both the project root and the working directory will be added to the `PYTHONPATH`.
**Example project structure:**
```
/root/
/other/
...
/tasks/
Dockerfile
task1.py
cowait.yml
README.md
```
```yml
version: 1
cowait:
workdir: tasks
```
```
$ pwd
/root/
$ cowait run task1
```
=> Task workdir setting

bin/cowait, cowait/cli/commands/agent.py, cowait/cli/commands/build.py, cowait/cli/commands/new_context.py, cowait/cli/commands/run.py, cowait/cli/commands/test.py, cowait/cli/context.py, cowait/cli/docker_file.py, cowait/cli/task_image.py, cowait/engine/docker.py
- Disables building of images without a `cowait.yml` file.
- Resolves configuration ambiguities.
- User-wide configuration lives in `~/.cowait.yml`
- Project settings live in `cowait.yml`. 
- CLI parameters can override both.
resolve #134
resolve #152
=> disable builds without a context file, clean up config ambiguities

cowait/cli/config.py
Running tasks on specific clusters failed due to an invalid setting of a private attribute with click.
`cowait run --cluster {cluster} {task}`
generated the following error
```bash
Traceback (most recent call last):
File "/home/emil/.local/bin/cowait", line 307, in <module>
cli(obj=config)
File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3/dist-packages/click/core.py", …
```
=> Setter for default_cluster, --cluster argument

cowait/engine/utils.py
Casting bytes to strings sometimes results in `b''` ending up in the output.
=> Properly encode input gzip as utf8 strings

cowait/exec.py, cowait/test/test_task.py
Ideally this PR should resolve all asyncio-related issues appearing in #115 
As of right now:
- Apply `nest_asyncio` patch to all tasks.
- Remove `nest_asyncio` patch from `cowait test` (since its applied everywhere)
Other things to try:
- Rewrite any `async for` loops
- Last resort: Supress `asyncio.CancelledError` from websocket sends.
resolve #175
=> Apply nest_asyncio patch for all tasks

cowait/cli/commands/run.py
Avoids logging potentially sensitive information. Should be re-introduced as a debugging feature at some point in the future.
resolve #172
=> Remove logging of environment variables on Task run

bin/cowait, cowait/cli/commands/build.py, cowait/cli/task_image.py
Adds two new arguments to `cowait build`:
- `--image <image name>`: Overrides the tag of the built image
- `--quiet`: Disables stdout logging
resolve #168
=> Build CLI Args: Quiet & Image name

cowait/engine/docker.py, cowait/engine/kubernetes.py, cowait/engine/test_kubernetes.py, pytest.ini
**Note:** Still very much untested 😄 
Adds basic support for kubernetes volumes
The volume type is specified by providing its options. Options are the same as for the kubernetes volume types, see
- [Host Path](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1HostPathVolumeSource.md)
- [NFS](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1NFSVolumeSource.md)
- [PersistentVolumeClaim](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PersistentVolumeClaimVolumeSource.md)
- etc
```python
await SomeVolumeTask(volumes={
'/container/target': {
'name': 'optional_volume_name',
'read_only': False,
'host_path': {
'path': '/host/source/path',
},
}
})
```
resolve #127
=> Basic support for Kubernetes Volumes

cowait/__init__.py, cowait/tasks/__init__.py, cowait/tasks/ops.py
- Removed depracted `gather` function, since it's no different from `join`.
- Added a `wait` function that waits for a list of tasks to complete without returning their results. Includes an option to ignore exceptions.
=> Improved task operators

bin/cowait, cowait/cli/commands/misc.py
Picked from @emilwareus PR
Perhaps this should be the default behaviour of `cowait kill` ?
=> Kill tasks by name/search

README.md, cowait/cli/app/image.py, cowait/cli/commands/build.py, cowait/cli/task_image.py
Adds support for passing build args to `cowait build` using `--arg` or `-a`.
Example:
```Dockerfile
FROM cowait/task
ARG SOME_VAR
RUN echo "some_var=$SOME_VAR"
```
```bash
$ cowait build --arg SOME_VAR 123
```
=> Add support for Docker build args

cowait/cli/app/cluster.py, cowait/cli/app/image.py, cowait/cli/app/task.py, cowait/cli/app/utils.py, test/cli/app/test_utils.py
- Add option parser for `key=value` CLI arguments
- Update `--input`, `--env`, `--route` options for `cowait run` to use `key=value` arguments
- Update `--arg`  option for `cowait build` to use `key=value` arguments
- Update `--option` option for `cowait cluster add` to use `key=value` arguments
resolve #209
=> Key=value input format

cowait/engine/kubernetes/kubernetes.py
Pull secrets specified in the podspec seem to override secrets attached to the service account. This means that you need to explicitly set an empty list of pull secrets to use SA secrets.
It also doesn't make sense for cowait to decide on what to name the user's pull secret.
=> Remove default pull secret for kubernetes

cowait/cli/app/task.py, cowait/cli/commands/run.py, cowait/engine/kubernetes/affinity.py, cowait/engine/kubernetes/kubernetes.py, cowait/engine/kubernetes/utils.py, cowait/tasks/definition.py, cowait/tasks/task.py, test/engine/kubernetes/test_affinity.py, test/tasks/test_definition.py
Provides two basic affinity settings for tasks:
- `stack`: Attempt to schedule with other tasks (kubernetes PodAffinity)
- `spread`: Attempt to spread evenly across nodes (kubernetes PodAntiAffinity)
The default mode is `spread`. Task affinity is inherited unless overridden by the `affinity` kwarg when calling `task.spawn()`.
Adds a `--affinity <mode>` argument to `cowait run`.
`--affinity spread` is equivalent to:
```yml
cowait:
affinity:
- mode: spread
required: false
namespaces:
- default
label: kubernetes.io/hostname
selectors:
- key: cowait/task
operator: Exists
```
`--affinity stack` is equivalent to:
```yml
cowait:
affinity:
- mode: stack
required: false
namespaces:
- default
label: kubernetes.io/hostname
selectors:
- key: cowait/task
operator: Exists
```
resolve #101
=> Task Affinity setting

cowait/cli/commands/cluster.py, cowait/cli/commands/push.py, cowait/cli/task_image.py, cowait/cli/utils.py, cowait/engine/kubernetes/errors.py, cowait/engine/kubernetes/kubernetes.py, cowait/engine/kubernetes/pod.py, cowait/engine/kubernetes/task.py, cowait/tasks/components/task_manager.py, cowait/tasks/remote_task.py, test/tasks/components/test_task_manager.py
Changes the default behavior of task timeouts. Cowait will now wait for indefinitely as long as no error (such as unavailable images etc) occur. 
resolve #243
=> Wait for unschedulable Kubernetes tasks

cowait/cli/app/root.py, cowait/cli/app/task.py, cowait/cli/commands/__init__.py, cowait/cli/commands/run.py, cowait/cli/commands/task.py, cowait/cli/commands/test.py, cowait/engine/cluster.py, cowait/engine/docker/docker.py, cowait/engine/docker/utils.py, cowait/engine/kubernetes/kubernetes.py, cowait/engine/kubernetes/pod.py, cowait/engine/kubernetes/utils.py, cowait/engine/utils.py, cowait/tasks/remote_task.py, test/engine/docker/test_docker.py, test/engine/docker/test_docker_util.py
- Changed `ClusterProvider.logs()` to take a task id string instead of a task object as its parameter 
- Added `cowait logs <task id>` to attach to a log output of a detached container
- Fixed `cowait kill` command
resolve #248
=> Log command & Engine cleanup

cowait/engine/kubernetes/kubernetes.py, poetry.lock, pyproject.toml, setup.py
Requires `kubernetes>=10` instead of `kubernetes>=12`
=> Ensure compatibility with older versions of python-kubernetes

cowait/engine/const.py
At Debricked, we are using some quite long secrets :) Some configurations we have are done through jsonified configurations, which results in some long strings for envs.
=> Increase max-length of env-variables

cowait/cli/app/task.py, cowait/cli/commands/test.py, cowait/engine/kubernetes/kubernetes.py, examples/test_examples.sh
- Remove built-in `build` and `push` functionality from `cowait test`
- Pass `environment` and `volumes` configuration when running `cowait test`
- Implement `KubernetesProvider.wait()` so that tests may run on kubernetes clusters. `wait()` should probably be removed or changes, since its API currently breaks the convention of passing task ids to `ClusterProvider` methods.
=> Test command fixes

cowait/cli/app/task.py, cowait/cli/commands/test.py, examples/test_examples.sh
- Add `--mount`/`--no-mount` flags to `cowait test`.
If `--mount` is set, the working directory is mounted into the container when running in Docker. Mount is enabled by default.
=> cowait test correctly mounts the context root when running locally

cowait/cli/app/image.py, cowait/cli/app/task.py, cowait/cli/commands/build.py, cowait/cli/context.py
We have tasks that need different builds, such as maven, npm etc. We simply name the dockerfiles differently to make the images slimmer where each dockerfile only contains its minimal needed environment.
=> Custom dockerfile names and wildcard-kill

cowait/cli/app/task.py, cowait/cli/commands/test.py, cowait/test/test_task.py
Adds two new flags:
- `--verbose` enables verbose output from pytest (false by default)
- `--capture` toggles output capturing (true by default)
Improved the pytest argument generation code
=> Improve cowait test

cowait/cli/commands/run.py, cowait/cli/commands/task.py, cowait/engine/kubernetes/kubernetes.py, cowait/engine/kubernetes/pod.py
- `logs` command now allows reading logs from terminated Kubernetes pods
- Logs show an error if the task appears to have been lost during execution (i.e. OOM killed or manually deleted)
=> Improve logs command

cowait/engine/kubernetes/kubernetes.py, test/engine/kubernetes/test_kubernetes.py
This test fails if the `KubernetesProvider` cannot be instantiated. Such a problem has already happened, and is being addressed by #344.
=> add simple test for kubernetes provider

cowait/network/client.py, cowait/network/server.py, poetry.lock, pyproject.toml
Disables websocket heartbeats in favour of a receive timeout. Clients will be dropped if no message is received for 30 seconds. Resource status messages are sent every ~10 seconds, which should keep the connection alive if there is no other activity.
=> Avoid socket timeout if IO loop is overloaded
